In [78]:
from sklearn import tree
import pandas as pd
import os
import numpy as np

In [79]:
dfraw = pd.read_csv(os.path.join("rg_proj2_resources/countydemographicsFINALPROJwithbrewcount.csv"))
dfzero = dfraw[dfraw["breweriesTOTALper10000"] == 0]
dfnonzero = dfraw[dfraw["breweriesTOTALper10000"] != 0]
dfnonzero

,fips_txt,Stabr,countyshort,countbrewpub,countcontract,countmicro,countregional,counttotal,countlargest,countbest,...,whitepercent,blackpercent,hispanicpercent,millennialpercent,genxpercent,boomerpercent,densitypermile,popchange,malepercent,femalepercent
0,8111,CO,San Juan,2,0,0,0,2,0,0,...,0.9464,0.0151,0.1250,0.1690,0.1964,0.3681,1.878768,0.0398,0.551,0.449
1,2230,AK,Skagway Municipality,2,0,0,0,2,0,0,...,0.8631,0.0144,0.0668,0.2933,0.2240,0.2282,2.615376,0.1817,0.524,0.476
2,35021,NM,Harding,0,0,1,0,1,0,0,...,0.9488,0.0080,0.4688,0.1360,0.1280,0.4000,0.294056,-0.1120,0.510,0.490
3,8053,CO,Hinsdale,1,0,0,0,1,0,0,...,0.9317,0.0256,0.0573,0.1280,0.1488,0.3707,0.733944,-0.0280,0.515,0.485
4,8091,CO,Ouray,3,0,1,0,4,0,0,...,0.9600,0.0081,0.0652,0.1383,0.1852,0.3910,9.143397,0.1042,0.507,0.493
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1279,49011,UT,Davis,0,0,1,0,1,0,0,...,0.9213,0.0221,0.1016,0.2174,0.1755,0.1559,1189.783050,0.1378,0.505,0.495
1280,12083,FL,Marion,0,0,1,0,1,0,0,...,0.8208,0.1467,0.1412,0.1613,0.1584,0.2937,230.715296,0.0938,0.479,0.521
1281,12097,FL,Osceola,0,0,0,0,1,0,0,...,0.7911,0.1602,0.5583,0.2177,0.2041,0.1902,283.061622,0.2849,0.494,0.506
1282,48061,TX,Cameron,1,0,0,0,1,0,0,...,0.9707,0.0099,0.9000,0.1843,0.1739,0.1757,474.971995,0.0400,0.488,0.512
1283,49049,UT,Utah,1,0,0,0,1,0,0,...,0.9270,0.0140,0.1217,0.2103,0.1470,0.1139,317.569058,0.1881,0.505,0.495

In [95]:
working_target = dfnonzero["breweriesTOTALper10000"]
from sklearn.cluster import KMeans
target = pd.qcut(working_target,2,labels=["low","high"])
target

0       high
1       high
2       high
3       high
4       high
        ...
1279     low
1280     low
1281     low
1282     low
1283     low
Name: breweriesTOTALper10000, Length: 1284, dtype: category
Categories (2, object): [low < high]

In [96]:
pd.value_counts(target)

high    642
low     642
Name: breweriesTOTALper10000, dtype: int64

In [97]:
dfnonzero['target_value'] = target
dfzero['target_value'] = "zero"

C:\Users\regro\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\regro\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [98]:
new_df = pd.concat([dfnonzero,dfzero.sample(n=642)],ignore_index=True,copy=True)
new_df

,fips_txt,Stabr,countyshort,countbrewpub,countcontract,countmicro,countregional,counttotal,countlargest,countbest,...,blackpercent,hispanicpercent,millennialpercent,genxpercent,boomerpercent,densitypermile,popchange,malepercent,femalepercent,target_value
0,8111,CO,San Juan,2,0,0,0,2,0,0,...,0.0151,0.1250,0.1690,0.1964,0.3681,1.878768,0.0398,0.551,0.449,high
1,2230,AK,Skagway Municipality,2,0,0,0,2,0,0,...,0.0144,0.0668,0.2933,0.2240,0.2282,2.615376,0.1817,0.524,0.476,high
2,35021,NM,Harding,0,0,1,0,1,0,0,...,0.0080,0.4688,0.1360,0.1280,0.4000,0.294056,-0.1120,0.510,0.490,high
3,8053,CO,Hinsdale,1,0,0,0,1,0,0,...,0.0256,0.0573,0.1280,0.1488,0.3707,0.733944,-0.0280,0.515,0.485,high
4,8091,CO,Ouray,3,0,1,0,4,0,0,...,0.0081,0.0652,0.1383,0.1852,0.3910,9.143397,0.1042,0.507,0.493,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1921,19077,IA,Guthrie,0,0,0,0,0,0,0,...,0.0118,0.0281,0.1502,0.1767,0.2836,18.097931,-0.0248,0.500,0.500,zero
1922,1017,AL,Chambers,0,0,0,0,0,0,0,...,0.4098,0.0262,0.1810,0.1864,0.2633,55.745636,-0.0289,0.478,0.522,zero
1923,48305,TX,Lynn,0,0,0,0,0,0,0,...,0.0351,0.4677,0.1897,0.1679,0.2163,6.672520,0.0060,0.513,0.487,zero
1924,18071,IN,Jackson,0,0,0,0,0,0,0,...,0.0198,0.0777,0.1884,0.1912,0.2278,86.844606,0.0419,0.500,0.500,zero
1925,48025,TX,Bee,0,0,0,0,0,0,0,...,0.0944,0.5932,0.2591,0.1936,0.1733,36.995634,0.0216,0.609,0.391,zero

In [99]:
y = new_df['target_value']

In [100]:
data = new_df.copy(deep=True)[['median_HHI_2019', 'bach_deg_pct_14to18','population2019', 'whitepercent', 'blackpercent',
       'hispanicpercent', 'millennialpercent', 'genxpercent', 'boomerpercent','densitypermile', 'popchange', 'malepercent']]
data = data.replace([np.inf, -np.inf], np.nan).fillna(data.mean())
data

,median_HHI_2019,bach_deg_pct_14to18,population2019,whitepercent,blackpercent,hispanicpercent,millennialpercent,genxpercent,boomerpercent,densitypermile,popchange,malepercent
0,50524,34.5,728,0.9464,0.0151,0.1250,0.1690,0.1964,0.3681,1.878768,0.0398,0.551
1,74898,33.7,1183,0.8631,0.0144,0.0668,0.2933,0.2240,0.2282,2.615376,0.1817,0.524
2,38162,24.3,625,0.9488,0.0080,0.4688,0.1360,0.1280,0.4000,0.294056,-0.1120,0.510
3,61391,43.9,820,0.9317,0.0256,0.0573,0.1280,0.1488,0.3707,0.733944,-0.0280,0.515
4,72836,48.6,4952,0.9600,0.0081,0.0652,0.1383,0.1852,0.3910,9.143397,0.1042,0.507
...,...,...,...,...,...,...,...,...,...,...,...,...
1921,64965,19.8,10689,0.9730,0.0118,0.0281,0.1502,0.1767,0.2836,18.097931,-0.0248,0.500
1922,42015,13.2,33254,0.5705,0.4098,0.0262,0.1810,0.1864,0.2633,55.745636,-0.0289,0.478
1923,45737,18.2,5951,0.9326,0.0351,0.4677,0.1897,0.1679,0.2163,6.672520,0.0060,0.513
1924,59472,15.5,44231,0.9387,0.0198,0.0777,0.1884,0.1912,0.2278,86.844606,0.0419,0.500
1925,44171,10.2,32565,0.8810,0.0944,0.5932,0.2591,0.1936,0.1733,36.995634,0.0216,0.609

In [101]:
data = data.astype('float32')

In [102]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, y, random_state=42)
print(X_train)
print(X_test)

      median_HHI_2019  bach_deg_pct_14to18  population2019  whitepercent  \
199           56948.0            35.700001         35470.0        0.9550
1537          43220.0            11.100000         24549.0        0.9573
1677          43902.0            10.600000          8954.0        0.5927
1161          59201.0            24.000000        309833.0        0.8615
1009          61691.0            24.700001        196311.0        0.8334
...               ...                  ...             ...           ...
1130          55745.0            23.400000        553947.0        0.8751
1294          53108.0            19.700001           748.0        0.9719
860           58339.0            29.200001        957755.0        0.6060
1459          39036.0            16.000000         20183.0        0.5856
1126          76972.0            38.599998        827370.0        0.6019

      blackpercent  hispanicpercent  millennialpercent  genxpercent  \
199         0.0200           0.0223             0.1502       0.1733
1537        0.0294           0.0173             0.1710       0.1938
1677        0.3919           0.0309             0.1677       0.1721
1161        0.1107           0.1039             0.1744       0.1907
1009        0.1373           0.1363             0.1835       0.1871
...            ...              ...                ...          ...
1130        0.0792           0.1654             0.1741       0.1911
1294        0.0053           0.0374             0.1551       0.1738
860         0.3245           0.1052             0.2355       0.1803
1459        0.4053           0.0160             0.1836       0.1730
1126        0.3200           0.0581             0.2011       0.1824

      boomerpercent  densitypermile  popchange  malepercent
199          0.2951       52.549706    -0.0467        0.487
1537         0.2459       73.479103    -0.0079        0.490
1677         0.2667       20.017527    -0.0680        0.480
1161         0.2536      630.894653     0.0274        0.492
1009         0.2471      590.407227     0.0046        0.496
...             ...             ...        ...          ...
1130         0.2593      741.675415     0.1611        0.486
1294         0.2767        1.310763    -0.0201        0.529
860          0.2164     1256.579712     0.0976        0.485
1459         0.2410       24.894234    -0.0279        0.480
1126         0.2361     1382.863525     0.0270        0.473

[1444 rows x 12 columns]
      median_HHI_2019  bach_deg_pct_14to18  population2019  whitepercent  \
1075          50973.0            23.500000         76978.0        0.9155
1650          29687.0            17.500000         28183.0        0.2313
1861          48165.0            12.500000         12728.0        0.8947
941           77375.0            26.600000        167417.0        0.3491
331           66211.0            31.299999         17258.0        0.9718
...               ...                  ...             ...           ...
1281          52270.0            20.500000        375751.0        0.7911
561           50803.0            20.900000         28530.0        0.9155
909          110252.0            54.400002        209177.0        0.8620
465           71733.0            30.500000        471519.0        0.8462
588           41964.0            14.300000         30104.0        0.9568

      blackpercent  hispanicpercent  millennialpercent  genxpercent  \
1075        0.0541           0.0316             0.1811       0.1880
1650        0.7550           0.0282             0.1858       0.1614
1861        0.0695           0.5814             0.2267       0.1571
941         0.0181           0.1157             0.1941       0.1925
331         0.0105           0.0220             0.1547       0.1670
...            ...              ...                ...          ...
1281        0.1602           0.5583             0.2177       0.2041
561         0.0658           0.0190             0.1841       0.1734
909         0.0484           0.0280             0.1720       0.2267
465         0.0393           0.2500             0.2192       0.1795
588         0.0310           0.0201             0.1654       0.1983

      boomerpercent  densitypermile  popchange  malepercent
1075         0.2605      228.311615     0.0240        0.487
1650         0.2081       47.563114    -0.1467        0.465
1861         0.1883       14.137416    -0.0868        0.547
941          0.2573      144.136002     0.0752        0.496
331          0.3105       45.343479     0.0342        0.497
...             ...             ...        ...          ...
1281         0.1902      283.061615     0.2849        0.494
561          0.2383       65.297394    -0.0088        0.486
909          0.2095      472.078400     0.1671        0.497
465          0.2373       74.816185     0.1063        0.505
588          0.2700       66.760101    -0.0699        0.489

[482 rows x 12 columns]

In [103]:
from sklearn.ensemble import RandomForestRegressor,RandomForestClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
# rf = RandomForestRegressor(n_estimators=200)
# rf = rf.fit(X_train, y_train)
# rf.score(X_test, y_test)

pipe = make_pipeline(StandardScaler(), RandomForestClassifier(n_estimators=1000, max_depth=6,n_jobs=-1))
rf = pipe.fit(X_train, y_train)  # apply scaling on training data

print(rf.score(X_test, y_test))

0.6493775933609959

In [104]:
from sklearn.metrics import classification_report

In [105]:
y_pred = rf.predict(X_test)
y_pred

array(['low', 'zero', 'zero', 'low', 'high', 'low', 'zero', 'zero',
       'zero', 'low', 'high', 'zero', 'low', 'low', 'zero', 'low', 'high',
       'low', 'zero', 'low', 'zero', 'high', 'zero', 'low', 'low', 'low',
       'zero', 'low', 'zero', 'high', 'low', 'zero', 'low', 'low', 'high',
       'high', 'low', 'zero', 'zero', 'low', 'zero', 'low', 'high', 'low',
       'high', 'high', 'zero', 'zero', 'low', 'low', 'low', 'low', 'low',
       'high', 'zero', 'high', 'low', 'low', 'low', 'high', 'low', 'zero',
       'zero', 'high', 'low', 'high', 'low', 'zero', 'zero', 'zero',
       'zero', 'low', 'low', 'low', 'high', 'low', 'high', 'high', 'zero',
       'high', 'low', 'zero', 'high', 'zero', 'high', 'high', 'zero',
       'low', 'zero', 'zero', 'zero', 'low', 'low', 'zero', 'low', 'zero',
       'high', 'high', 'high', 'zero', 'zero', 'high', 'high', 'zero',
       'zero', 'high', 'low', 'low', 'high', 'zero', 'high', 'low', 'low',
       'high', 'zero', 'high', 'high', 'zero', 'low', 'zero', 'high',
       'high', 'zero', 'low', 'zero', 'low', 'low', 'high', 'zero', 'low',
       'high', 'zero', 'low', 'zero', 'zero', 'low', 'low', 'high',
       'zero', 'low', 'low', 'zero', 'low', 'zero', 'low', 'low', 'zero',
       'low', 'zero', 'zero', 'low', 'low', 'zero', 'zero', 'high',
       'zero', 'zero', 'low', 'high', 'zero', 'high', 'zero', 'high',
       'low', 'low', 'zero', 'low', 'zero', 'zero', 'zero', 'high', 'low',
       'low', 'low', 'zero', 'low', 'high', 'zero', 'low', 'high', 'low',
       'zero', 'low', 'low', 'zero', 'low', 'low', 'zero', 'low', 'high',
       'zero', 'high', 'low', 'low', 'high', 'high', 'high', 'low',
       'zero', 'high', 'low', 'zero', 'high', 'low', 'high', 'high',
       'zero', 'zero', 'low', 'zero', 'high', 'low', 'zero', 'high',
       'low', 'low', 'high', 'zero', 'high', 'low', 'zero', 'zero',
       'zero', 'zero', 'low', 'zero', 'zero', 'zero', 'high', 'low',
       'high', 'low', 'zero', 'low', 'low', 'low', 'low', 'high', 'high',
       'low', 'low', 'zero', 'high', 'low', 'high', 'low', 'zero', 'high',
       'zero', 'zero', 'high', 'low', 'high', 'low', 'low', 'low', 'high',
       'zero', 'high', 'zero', 'low', 'zero', 'zero', 'zero', 'low',
       'zero', 'zero', 'zero', 'high', 'low', 'low', 'zero', 'zero',
       'zero', 'low', 'zero', 'zero', 'low', 'low', 'high', 'low', 'high',
       'low', 'low', 'zero', 'low', 'low', 'high', 'high', 'low', 'zero',
       'high', 'zero', 'low', 'high', 'low', 'zero', 'low', 'zero',
       'zero', 'zero', 'low', 'zero', 'zero', 'low', 'high', 'zero',
       'high', 'low', 'low', 'high', 'low', 'high', 'low', 'low', 'high',
       'low', 'zero', 'zero', 'low', 'zero', 'high', 'zero', 'low', 'low',
       'low', 'zero', 'high', 'low', 'low', 'zero', 'high', 'zero', 'low',
       'zero', 'zero', 'high', 'low', 'low', 'zero', 'low', 'low', 'high',
       'zero', 'low', 'high', 'zero', 'low', 'low', 'high', 'high', 'low',
       'low', 'low', 'zero', 'low', 'low', 'high', 'high', 'high', 'zero',
       'zero', 'high', 'low', 'high', 'zero', 'low', 'low', 'high',
       'zero', 'low', 'low', 'low', 'low', 'low', 'low', 'zero', 'zero',
       'low', 'zero', 'high', 'low', 'zero', 'high', 'low', 'zero',
       'zero', 'high', 'zero', 'low', 'zero', 'low', 'low', 'high', 'low',
       'low', 'low', 'zero', 'high', 'high', 'zero', 'zero', 'high',
       'high', 'low', 'low', 'low', 'zero', 'low', 'low', 'low', 'zero',
       'zero', 'zero', 'low', 'zero', 'low', 'low', 'zero', 'high', 'low',
       'high', 'high', 'high', 'zero', 'high', 'low', 'low', 'low', 'low',
       'high', 'low', 'high', 'zero', 'high', 'low', 'zero', 'high',
       'high', 'zero', 'low', 'zero', 'low', 'low', 'low', 'low', 'low',
       'low', 'low', 'high', 'low', 'low', 'low', 'low', 'zero', 'high',
       'low', 'low', 'low', 'low', 'high', 'zero', 'low', 'zero', 'zero',
       'zero', 'zero', 'zero', 'zero', 'high', 'zero', 'zero', 'low',
       'low', 'high', 'low', 'low', 'low', 'zero', 'low', 'low', 'zero'],
      dtype=object)

In [106]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        high       0.64      0.44      0.52       174
         low       0.57      0.83      0.68       139
        zero       0.75      0.72      0.73       169

    accuracy                           0.65       482
   macro avg       0.65      0.66      0.64       482
weighted avg       0.66      0.65      0.64       482

In [90]:
# import sklearn.metrics as metrics
# def regression_results(y_true, y_pred):
#     # Regression metrics
#     explained_variance=metrics.explained_variance_score(y_true, y_pred)
#     mean_absolute_error=metrics.mean_absolute_error(y_true, y_pred) 
#     mse=metrics.mean_squared_error(y_true, y_pred) 
#     mean_squared_log_error=metrics.mean_squared_log_error(y_true, y_pred)
#     median_absolute_error=metrics.median_absolute_error(y_true, y_pred)
#     r2=metrics.r2_score(y_true, y_pred)
#     print('explained_variance: ', round(explained_variance,4))    
#     print('mean_squared_log_error: ', round(mean_squared_log_error,4))
#     print('r2: ', round(r2,4))
#     print('MAE: ', round(mean_absolute_error,4))
#     print('MSE: ', round(mse,4))
#     print('RMSE: ', round(np.sqrt(mse),4))

In [10]:
regression_results(y_test,y_pred)

explained_variance:  0.0
mean_squared_log_error:  0.0024
r2:  -0.0013
MAE:  0.0038
MSE:  0.0115
RMSE:  0.1071

In [107]:
df['expectedbreweriesbin'] = rf.predict(data)
# df['diffexpectedbreweriesvreal'] = df['expectedbreweriesper10k']-df['breweriesTOTALper10000']
df

ValueError: Length of values does not match length of index

In [13]:
df['target'] = target
df[['target','breweriesTOTALper10000']].sort_values('breweriesTOTALper10000')

     target  breweriesTOTALper10000
1569      0                0.000000
2088      0                0.000000
2089      0                0.000000
2090      0                0.000000
2091      0                0.000000
...     ...                     ...
4         1                8.077544
3         1               12.195122
2         2               16.000000
1         2               16.906171
0         3               27.472527

[3140 rows x 2 columns]