In [1]:
from sklearn import tree
import pandas as pd
import os
import numpy as np

In [2]:
dfraw = pd.read_csv(os.path.join("rg_proj2_resources/countydemographicsFINALPROJwithbrewcount.csv"))
dfzero = dfraw[dfraw["breweriesTOTALper10000"] == 0]
dfnonzero = dfraw[dfraw["breweriesTOTALper10000"] != 0]
dfnonzero

,fips_txt,Stabr,countyshort,countbrewpub,countcontract,countmicro,countregional,counttotal,countlargest,countbest,...,whitepercent,blackpercent,hispanicpercent,millennialpercent,genxpercent,boomerpercent,densitypermile,popchange,malepercent,femalepercent
0,8111,CO,San Juan,2,0,0,0,2,0,0,...,0.9464,0.0151,0.1250,0.1690,0.1964,0.3681,1.878768,0.0398,0.551,0.449
1,2230,AK,Skagway Municipality,2,0,0,0,2,0,0,...,0.8631,0.0144,0.0668,0.2933,0.2240,0.2282,2.615376,0.1817,0.524,0.476
2,35021,NM,Harding,0,0,1,0,1,0,0,...,0.9488,0.0080,0.4688,0.1360,0.1280,0.4000,0.294056,-0.1120,0.510,0.490
3,8053,CO,Hinsdale,1,0,0,0,1,0,0,...,0.9317,0.0256,0.0573,0.1280,0.1488,0.3707,0.733944,-0.0280,0.515,0.485
4,8091,CO,Ouray,3,0,1,0,4,0,0,...,0.9600,0.0081,0.0652,0.1383,0.1852,0.3910,9.143397,0.1042,0.507,0.493
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1279,49011,UT,Davis,0,0,1,0,1,0,0,...,0.9213,0.0221,0.1016,0.2174,0.1755,0.1559,1189.783050,0.1378,0.505,0.495
1280,12083,FL,Marion,0,0,1,0,1,0,0,...,0.8208,0.1467,0.1412,0.1613,0.1584,0.2937,230.715296,0.0938,0.479,0.521
1281,12097,FL,Osceola,0,0,0,0,1,0,0,...,0.7911,0.1602,0.5583,0.2177,0.2041,0.1902,283.061622,0.2849,0.494,0.506
1282,48061,TX,Cameron,1,0,0,0,1,0,0,...,0.9707,0.0099,0.9000,0.1843,0.1739,0.1757,474.971995,0.0400,0.488,0.512
1283,49049,UT,Utah,1,0,0,0,1,0,0,...,0.9270,0.0140,0.1217,0.2103,0.1470,0.1139,317.569058,0.1881,0.505,0.495

In [3]:
working_target = dfnonzero["breweriesTOTALper10000"]
from sklearn.cluster import KMeans
target = pd.qcut(working_target,2,labels=["low","high"])
target

0       high
1       high
2       high
3       high
4       high
        ...
1279     low
1280     low
1281     low
1282     low
1283     low
Name: breweriesTOTALper10000, Length: 1284, dtype: category
Categories (2, object): [low < high]

In [4]:
pd.value_counts(target)

high    642
low     642
Name: breweriesTOTALper10000, dtype: int64

In [5]:
dfnonzero['target_value'] = target
dfzero['target_value'] = "zero"

C:\Users\regro\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\regro\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [6]:
new_df = pd.concat([dfnonzero,dfzero.sample(n=642)],ignore_index=True,copy=True)
new_df

,fips_txt,Stabr,countyshort,countbrewpub,countcontract,countmicro,countregional,counttotal,countlargest,countbest,...,blackpercent,hispanicpercent,millennialpercent,genxpercent,boomerpercent,densitypermile,popchange,malepercent,femalepercent,target_value
0,8111,CO,San Juan,2,0,0,0,2,0,0,...,0.0151,0.1250,0.1690,0.1964,0.3681,1.878768,0.0398,0.551,0.449,high
1,2230,AK,Skagway Municipality,2,0,0,0,2,0,0,...,0.0144,0.0668,0.2933,0.2240,0.2282,2.615376,0.1817,0.524,0.476,high
2,35021,NM,Harding,0,0,1,0,1,0,0,...,0.0080,0.4688,0.1360,0.1280,0.4000,0.294056,-0.1120,0.510,0.490,high
3,8053,CO,Hinsdale,1,0,0,0,1,0,0,...,0.0256,0.0573,0.1280,0.1488,0.3707,0.733944,-0.0280,0.515,0.485,high
4,8091,CO,Ouray,3,0,1,0,4,0,0,...,0.0081,0.0652,0.1383,0.1852,0.3910,9.143397,0.1042,0.507,0.493,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1921,13055,GA,Chattooga,0,0,0,0,0,0,0,...,0.1115,0.0549,0.1892,0.1915,0.2382,79.112652,-0.0495,0.510,0.490,zero
1922,51199,VA,York,0,0,0,0,0,0,0,...,0.1568,0.0688,0.1877,0.1878,0.2327,651.651079,0.0412,0.491,0.509,zero
1923,21059,KY,Daviess,0,0,0,0,0,0,0,...,0.0684,0.0330,0.1917,0.1763,0.2337,221.472425,0.0478,0.488,0.512,zero
1924,22095,LA,St. John the Baptist,0,0,0,0,0,0,0,...,0.5929,0.0667,0.1981,0.1830,0.2340,201.045661,-0.0721,0.488,0.512,zero
1925,48281,TX,Lampasas,0,0,0,0,0,0,0,...,0.0524,0.1940,0.1629,0.1932,0.2684,30.060042,0.0817,0.491,0.509,zero

In [7]:
y = new_df['target_value']

In [8]:
data = new_df.copy(deep=True)[['median_HHI_2019', 'bach_deg_pct_14to18','population2019', 'whitepercent', 'blackpercent',
       'hispanicpercent', 'millennialpercent', 'genxpercent', 'boomerpercent','densitypermile', 'popchange', 'malepercent']]
data = data.replace([np.inf, -np.inf], np.nan).fillna(data.mean())
data

,median_HHI_2019,bach_deg_pct_14to18,population2019,whitepercent,blackpercent,hispanicpercent,millennialpercent,genxpercent,boomerpercent,densitypermile,popchange,malepercent
0,50524,34.5,728,0.9464,0.0151,0.1250,0.1690,0.1964,0.3681,1.878768,0.0398,0.551
1,74898,33.7,1183,0.8631,0.0144,0.0668,0.2933,0.2240,0.2282,2.615376,0.1817,0.524
2,38162,24.3,625,0.9488,0.0080,0.4688,0.1360,0.1280,0.4000,0.294056,-0.1120,0.510
3,61391,43.9,820,0.9317,0.0256,0.0573,0.1280,0.1488,0.3707,0.733944,-0.0280,0.515
4,72836,48.6,4952,0.9600,0.0081,0.0652,0.1383,0.1852,0.3910,9.143397,0.1042,0.507
...,...,...,...,...,...,...,...,...,...,...,...,...
1921,41561,9.8,24789,0.8679,0.1115,0.0549,0.1892,0.1915,0.2382,79.112652,-0.0495,0.510
1922,91535,45.4,68280,0.7537,0.1568,0.0688,0.1877,0.1878,0.2327,651.651079,0.0412,0.491
1923,52620,22.9,101511,0.9043,0.0684,0.0330,0.1917,0.1763,0.2337,221.472425,0.0478,0.488
1924,54944,16.3,42837,0.3839,0.5929,0.0667,0.1981,0.1830,0.2340,201.045661,-0.0721,0.488
1925,58817,20.0,21428,0.8982,0.0524,0.1940,0.1629,0.1932,0.2684,30.060042,0.0817,0.491

In [9]:
data = data.astype('float32')

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, y, random_state=42)

In [11]:
from sklearn.ensemble import RandomForestRegressor,RandomForestClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
# rf = RandomForestRegressor(n_estimators=200)
# rf = rf.fit(X_train, y_train)
# rf.score(X_test, y_test)

pipe = make_pipeline(StandardScaler(), RandomForestClassifier(n_estimators=1000, max_depth=6,n_jobs=-1))
rf = pipe.fit(X_train, y_train)  # apply scaling on training data

print(rf.score(X_test, y_test))

0.6514522821576764

In [12]:
from sklearn.metrics import classification_report

In [13]:
y_pred = rf.predict(X_test)
y_pred

array(['low', 'zero', 'zero', 'low', 'high', 'low', 'high', 'zero',
       'zero', 'low', 'zero', 'high', 'low', 'low', 'low', 'low', 'high',
       'low', 'zero', 'low', 'low', 'high', 'zero', 'low', 'low', 'low',
       'zero', 'low', 'zero', 'zero', 'low', 'zero', 'low', 'low', 'high',
       'high', 'low', 'zero', 'zero', 'low', 'zero', 'low', 'zero', 'low',
       'high', 'high', 'zero', 'high', 'low', 'low', 'low', 'low', 'zero',
       'high', 'zero', 'low', 'low', 'low', 'zero', 'zero', 'low', 'zero',
       'zero', 'high', 'low', 'high', 'low', 'zero', 'zero', 'high',
       'zero', 'low', 'low', 'low', 'high', 'low', 'high', 'high', 'zero',
       'high', 'low', 'zero', 'high', 'zero', 'high', 'zero', 'zero',
       'low', 'zero', 'zero', 'zero', 'low', 'low', 'zero', 'low', 'zero',
       'high', 'high', 'zero', 'high', 'zero', 'high', 'low', 'zero',
       'zero', 'high', 'low', 'low', 'high', 'high', 'high', 'zero',
       'low', 'high', 'zero', 'high', 'high', 'zero', 'low', 'zero',
       'high', 'high', 'high', 'low', 'zero', 'low', 'low', 'high',
       'zero', 'low', 'high', 'zero', 'low', 'zero', 'zero', 'low', 'low',
       'high', 'zero', 'low', 'low', 'zero', 'low', 'zero', 'low', 'low',
       'zero', 'low', 'zero', 'zero', 'low', 'low', 'zero', 'zero',
       'high', 'zero', 'zero', 'zero', 'high', 'zero', 'high', 'zero',
       'zero', 'low', 'low', 'zero', 'low', 'high', 'zero', 'zero',
       'high', 'low', 'low', 'zero', 'zero', 'low', 'zero', 'zero', 'low',
       'high', 'low', 'zero', 'low', 'low', 'zero', 'low', 'low', 'high',
       'low', 'high', 'zero', 'high', 'zero', 'low', 'high', 'high',
       'high', 'low', 'zero', 'zero', 'zero', 'high', 'high', 'low',
       'zero', 'low', 'zero', 'zero', 'low', 'zero', 'high', 'low',
       'zero', 'zero', 'low', 'low', 'high', 'high', 'high', 'zero',
       'zero', 'zero', 'zero', 'zero', 'low', 'zero', 'high', 'zero',
       'high', 'low', 'low', 'low', 'zero', 'low', 'low', 'low', 'low',
       'high', 'high', 'low', 'low', 'zero', 'high', 'low', 'high', 'low',
       'zero', 'zero', 'low', 'high', 'high', 'low', 'high', 'low', 'low',
       'low', 'high', 'zero', 'zero', 'zero', 'low', 'zero', 'low', 'low',
       'low', 'zero', 'zero', 'zero', 'high', 'low', 'low', 'high',
       'zero', 'low', 'low', 'zero', 'zero', 'zero', 'zero', 'high',
       'low', 'high', 'low', 'zero', 'zero', 'zero', 'low', 'high',
       'high', 'low', 'zero', 'high', 'zero', 'low', 'high', 'low',
       'zero', 'low', 'zero', 'low', 'zero', 'low', 'high', 'zero', 'low',
       'high', 'zero', 'high', 'low', 'low', 'high', 'low', 'high',
       'zero', 'low', 'high', 'low', 'zero', 'zero', 'low', 'zero', 'low',
       'zero', 'low', 'low', 'low', 'zero', 'high', 'low', 'low', 'zero',
       'high', 'zero', 'low', 'zero', 'zero', 'zero', 'zero', 'low',
       'zero', 'zero', 'low', 'zero', 'zero', 'low', 'high', 'zero',
       'low', 'low', 'low', 'zero', 'low', 'zero', 'low', 'low', 'low',
       'zero', 'high', 'low', 'high', 'zero', 'zero', 'high', 'low',
       'high', 'low', 'low', 'low', 'high', 'zero', 'low', 'low', 'low',
       'low', 'zero', 'low', 'high', 'zero', 'low', 'zero', 'high', 'low',
       'zero', 'zero', 'low', 'zero', 'zero', 'high', 'zero', 'low',
       'zero', 'low', 'low', 'high', 'low', 'low', 'low', 'zero', 'high',
       'high', 'zero', 'zero', 'low', 'high', 'low', 'zero', 'low',
       'zero', 'low', 'low', 'low', 'zero', 'zero', 'zero', 'low', 'zero',
       'low', 'low', 'zero', 'high', 'low', 'low', 'high', 'high', 'zero',
       'high', 'zero', 'low', 'low', 'low', 'high', 'low', 'high', 'zero',
       'high', 'low', 'zero', 'high', 'high', 'zero', 'zero', 'high',
       'low', 'zero', 'low', 'low', 'low', 'low', 'low', 'high', 'low',
       'low', 'low', 'low', 'zero', 'high', 'low', 'low', 'zero', 'zero',
       'high', 'zero', 'low', 'zero', 'zero', 'zero', 'zero', 'zero',
       'zero', 'high', 'zero', 'zero', 'low', 'low', 'high', 'low', 'low',
       'low', 'zero', 'low', 'low', 'zero'], dtype=object)

In [14]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        high       0.64      0.40      0.49       174
         low       0.59      0.83      0.69       139
        zero       0.72      0.76      0.74       169

    accuracy                           0.65       482
   macro avg       0.65      0.66      0.64       482
weighted avg       0.66      0.65      0.64       482

In [90]:
# import sklearn.metrics as metrics
# def regression_results(y_true, y_pred):
#     # Regression metrics
#     explained_variance=metrics.explained_variance_score(y_true, y_pred)
#     mean_absolute_error=metrics.mean_absolute_error(y_true, y_pred) 
#     mse=metrics.mean_squared_error(y_true, y_pred) 
#     mean_squared_log_error=metrics.mean_squared_log_error(y_true, y_pred)
#     median_absolute_error=metrics.median_absolute_error(y_true, y_pred)
#     r2=metrics.r2_score(y_true, y_pred)
#     print('explained_variance: ', round(explained_variance,4))    
#     print('mean_squared_log_error: ', round(mean_squared_log_error,4))
#     print('r2: ', round(r2,4))
#     print('MAE: ', round(mean_absolute_error,4))
#     print('MSE: ', round(mse,4))
#     print('RMSE: ', round(np.sqrt(mse),4))

In [15]:
# regression_results(y_test,y_pred)

In [17]:
new_df['expectedbreweriesbin'] = rf.predict(data)
# df['diffexpectedbreweriesvreal'] = df['expectedbreweriesper10k']-df['breweriesTOTALper10000']
new_df

,fips_txt,Stabr,countyshort,countbrewpub,countcontract,countmicro,countregional,counttotal,countlargest,countbest,...,hispanicpercent,millennialpercent,genxpercent,boomerpercent,densitypermile,popchange,malepercent,femalepercent,target_value,expectedbreweriesbin
0,8111,CO,San Juan,2,0,0,0,2,0,0,...,0.1250,0.1690,0.1964,0.3681,1.878768,0.0398,0.551,0.449,high,high
1,2230,AK,Skagway Municipality,2,0,0,0,2,0,0,...,0.0668,0.2933,0.2240,0.2282,2.615376,0.1817,0.524,0.476,high,high
2,35021,NM,Harding,0,0,1,0,1,0,0,...,0.4688,0.1360,0.1280,0.4000,0.294056,-0.1120,0.510,0.490,high,zero
3,8053,CO,Hinsdale,1,0,0,0,1,0,0,...,0.0573,0.1280,0.1488,0.3707,0.733944,-0.0280,0.515,0.485,high,high
4,8091,CO,Ouray,3,0,1,0,4,0,0,...,0.0652,0.1383,0.1852,0.3910,9.143397,0.1042,0.507,0.493,high,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1921,13055,GA,Chattooga,0,0,0,0,0,0,0,...,0.0549,0.1892,0.1915,0.2382,79.112652,-0.0495,0.510,0.490,zero,zero
1922,51199,VA,York,0,0,0,0,0,0,0,...,0.0688,0.1877,0.1878,0.2327,651.651079,0.0412,0.491,0.509,zero,low
1923,21059,KY,Daviess,0,0,0,0,0,0,0,...,0.0330,0.1917,0.1763,0.2337,221.472425,0.0478,0.488,0.512,zero,low
1924,22095,LA,St. John the Baptist,0,0,0,0,0,0,0,...,0.0667,0.1981,0.1830,0.2340,201.045661,-0.0721,0.488,0.512,zero,zero
1925,48281,TX,Lampasas,0,0,0,0,0,0,0,...,0.1940,0.1629,0.1932,0.2684,30.060042,0.0817,0.491,0.509,zero,zero

In [18]:
fulldata = dfraw.copy(deep=True)[['median_HHI_2019', 'bach_deg_pct_14to18','population2019', 'whitepercent', 'blackpercent',
       'hispanicpercent', 'millennialpercent', 'genxpercent', 'boomerpercent','densitypermile', 'popchange', 'malepercent']]
fulldata = fulldata.replace([np.inf, -np.inf], np.nan).fillna(data.mean())
dfraw['expectedbreweriesbin'] = rf.predict(fulldata)
dfraw

,fips_txt,Stabr,countyshort,countbrewpub,countcontract,countmicro,countregional,counttotal,countlargest,countbest,...,blackpercent,hispanicpercent,millennialpercent,genxpercent,boomerpercent,densitypermile,popchange,malepercent,femalepercent,expectedbreweriesbin
0,8111,CO,San Juan,2,0,0,0,2,0,0,...,0.0151,0.1250,0.1690,0.1964,0.3681,1.878768,0.0398,0.551,0.449,high
1,2230,AK,Skagway Municipality,2,0,0,0,2,0,0,...,0.0144,0.0668,0.2933,0.2240,0.2282,2.615376,0.1817,0.524,0.476,high
2,35021,NM,Harding,0,0,1,0,1,0,0,...,0.0080,0.4688,0.1360,0.1280,0.4000,0.294056,-0.1120,0.510,0.490,zero
3,8053,CO,Hinsdale,1,0,0,0,1,0,0,...,0.0256,0.0573,0.1280,0.1488,0.3707,0.733944,-0.0280,0.515,0.485,high
4,8091,CO,Ouray,3,0,1,0,4,0,0,...,0.0081,0.0652,0.1383,0.1852,0.3910,9.143397,0.1042,0.507,0.493,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3135,56027,WY,Niobrara,0,0,0,0,0,0,0,...,0.0140,0.0403,0.2003,0.1711,0.2738,0.897169,-0.0543,0.458,0.542,zero
3136,56031,WY,Platte,0,0,0,0,0,0,0,...,0.0114,0.0840,0.1541,0.1663,0.3023,4.026949,-0.0326,0.503,0.497,high
3137,56035,WY,Sublette,0,0,0,0,0,0,0,...,0.0135,0.0714,0.1775,0.1920,0.2693,2.011854,-0.0423,0.536,0.464,high
3138,56043,WY,Washakie,0,0,0,0,0,0,0,...,0.0119,0.1420,0.1630,0.1754,0.2666,3.486634,-0.0933,0.508,0.492,zero
3139,56045,WY,Weston,0,0,0,0,0,0,0,...,0.0143,0.0411,0.1869,0.1675,0.2893,2.888550,-0.0406,0.523,0.477,zero

In [19]:
dfhigh = dfraw[dfraw["expectedbreweriesbin"] == "high"]
dflow = dfraw[dfraw["expectedbreweriesbin"] == "low"]
dfzeroresults = dfraw[dfraw["expectedbreweriesbin"] == "zero"]

In [52]:
dfnonzero['breweriesTOTALper10000'].describe()

count    1284.000000
mean        0.556894
std         1.205838
min         0.015717
25%         0.171717
50%         0.305731
75%         0.594234
max        27.472527
Name: breweriesTOTALper10000, dtype: float64

In [53]:
percentile25 = dfnonzero['breweriesTOTALper10000'].describe()['25%']
percentile75 = dfnonzero['breweriesTOTALper10000'].describe()['75%']

In [54]:
dfhigh['breweriesTOTALper10000'].describe()

count    641.000000
mean       0.650201
std        1.529723
min        0.000000
25%        0.000000
50%        0.393283
75%        0.811688
max       27.472527
Name: breweriesTOTALper10000, dtype: float64

In [55]:
dflow['breweriesTOTALper10000'].describe()

count    972.000000
mean       0.181247
std        0.179680
min        0.000000
25%        0.053461
50%        0.152854
75%        0.248877
max        1.460387
Name: breweriesTOTALper10000, dtype: float64

In [56]:
dfzeroresults['breweriesTOTALper10000'].describe()

count    1527.000000
mean        0.079961
std         0.525921
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max        16.000000
Name: breweriesTOTALper10000, dtype: float64

In [57]:
dfraw["expectedbreweriesbin"][0]
print(range(len(dfraw["expectedbreweriesbin"])))

range(0, 3140)

In [58]:
newcolumn = []

for i in range(len(dfraw["expectedbreweriesbin"])):
    if dfraw["expectedbreweriesbin"][i] == "high":
        minbrewerysustained = percentile75 * dfraw["population2019"][i] / 10000
        newcolumn.append(minbrewerysustained)
    elif dfraw["expectedbreweriesbin"][i] == "low":
        minbrewerysustained = percentile25 * dfraw["population2019"][i] / 10000
        newcolumn.append(minbrewerysustained)
    elif dfraw["expectedbreweriesbin"][i] == "zero":
        minbrewerysustained = 0
        newcolumn.append(minbrewerysustained)
    else:
        newcolumn.append("ERROR")
        
countylist = []

for i in range(len(dfraw["countyshort"])):
    newcountyname = ""
    newcountyname = newcountyname.join([dfraw["countyshort"][i],", ",dfraw["Stabr"][i]])
    countylist.append(newcountyname)

dfraw['expectedminbrewerysustained'] = newcolumn
dfraw['fullcounty'] = countylist

dfraw

,fips_txt,Stabr,countyshort,countbrewpub,countcontract,countmicro,countregional,counttotal,countlargest,countbest,...,millennialpercent,genxpercent,boomerpercent,densitypermile,popchange,malepercent,femalepercent,expectedbreweriesbin,expectedminbrewerysustained,fullcounty
0,8111,CO,San Juan,2,0,0,0,2,0,0,...,0.1690,0.1964,0.3681,1.878768,0.0398,0.551,0.449,high,0.043260,"San Juan, CO"
1,2230,AK,Skagway Municipality,2,0,0,0,2,0,0,...,0.2933,0.2240,0.2282,2.615376,0.1817,0.524,0.476,high,0.070298,"Skagway Municipality, AK"
2,35021,NM,Harding,0,0,1,0,1,0,0,...,0.1360,0.1280,0.4000,0.294056,-0.1120,0.510,0.490,zero,0.000000,"Harding, NM"
3,8053,CO,Hinsdale,1,0,0,0,1,0,0,...,0.1280,0.1488,0.3707,0.733944,-0.0280,0.515,0.485,high,0.048727,"Hinsdale, CO"
4,8091,CO,Ouray,3,0,1,0,4,0,0,...,0.1383,0.1852,0.3910,9.143397,0.1042,0.507,0.493,high,0.294265,"Ouray, CO"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3135,56027,WY,Niobrara,0,0,0,0,0,0,0,...,0.2003,0.1711,0.2738,0.897169,-0.0543,0.458,0.542,zero,0.000000,"Niobrara, WY"
3136,56031,WY,Platte,0,0,0,0,0,0,0,...,0.1541,0.1663,0.3023,4.026949,-0.0326,0.503,0.497,high,0.498741,"Platte, WY"
3137,56035,WY,Sublette,0,0,0,0,0,0,0,...,0.1775,0.1920,0.2693,2.011854,-0.0423,0.536,0.464,high,0.584192,"Sublette, WY"
3138,56043,WY,Washakie,0,0,0,0,0,0,0,...,0.1630,0.1754,0.2666,3.486634,-0.0933,0.508,0.492,zero,0.000000,"Washakie, WY"
3139,56045,WY,Weston,0,0,0,0,0,0,0,...,0.1869,0.1675,0.2893,2.888550,-0.0406,0.523,0.477,zero,0.000000,"Weston, WY"

In [59]:
dfraw.to_csv('ML_minbreweriesexpectedpercounty.csv')